# Uncomment the following line to force asset compression in development
#package_assets: always

# Embed that small background image
embed_assets: on

javascripts:
  common:
    - public/javascripts/jquery-1.4.2.js
    - public/javascripts/jquery-ujs/src/rails.js
    - public/javascripts/application.js
  map:
    - public/javascripts/map.js

stylesheets:
  map:
    - public/stylesheets/new.css
  backend:
    - public/stylesheets/general.css
